//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityOrnek
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteri
    {
        public decimal id { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string sehir { get; set; }
        public string adres { get; set; }
    }
}
